# Generated by Django 5.1.3 on 2025-11-29 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='collection_name',
            field=models.CharField(blank=True, default=None, help_text='Collection/category name for grouping conversations', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'collection_name', '-updated_at'], name='chat_conver_user_id_598af8_idx'),
        ),
    ]
